import 'package:flutter/material.dart';

import '../../core/theme/mobile_theme.dart';
import '../../core/theme/mobile_colors.dart';

/// 表情选择面板组件
/// 网格展示 emoji，支持分类 tab 和点击插入回调
class EmojiBar extends StatefulWidget {
  /// 表情被点击时的回调，传入 emoji 字符串
  final void Function(String emoji) onEmojiSelected;

  /// 是否显示分类 tab
  final bool showTabs;

  const EmojiBar({
    super.key,
    required this.onEmojiSelected,
    this.showTabs = false,
  });

  @override
  State<EmojiBar> createState() => _EmojiBarState();
}

class _EmojiBarState extends State<EmojiBar>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  // 表情分类
  static const _categories = [
    _EmojiCategory('最近', null),
    _EmojiCategory('😀', '😀 笑脸'),
    _EmojiCategory('❤️', '❤️ 情感'),
    _EmojiCategory('👀', '👀 人物'),
    _EmojiCategory('🐶', '🐶 动物'),
    _EmojiCategory('🍎', '🍎 食物'),
    _EmojiCategory('⚽', '⚽ 活动'),
    _EmojiCategory('🌈', '🌈 旅行'),
    _EmojiCategory('💡', '💡 物品'),
    _EmojiCategory('🔣', '🔣 符号'),
  ];

  // 分类对应的 emoji 列表
  static const _categoryEmojis = {
    null: [
      // 最近（默认一些常用 emoji）
      '😀', '😃', '😄', '😁', '😆', '😅', '🤣', '😂',
      '😍', '🤩', '🥰', '😘', '😋', '😜', '🤔', '👍',
      '👎', '👏', '🙏', '💪', '❤️', '🔥', '✨', '🎉',
      '😂', '😭', '😮', '🤯', '😎', '🥺', '😤', '🤢',
    ],
    '😀': [
      '😀',
      '😃',
      '😄',
      '😁',
      '😆',
      '😅',
      '🤣',
      '😂',
      '🙂',
      '😉',
      '😊',
      '😇',
      '🥰',
      '😍',
      '🤩',
      '😘',
      '😋',
      '😛',
      '😜',
      '🤪',
      '😝',
      '🤗',
      '🤭',
      '🤫',
      '🤔',
      '🤐',
      '🤨',
      '😐',
      '😑',
      '😶',
      '😏',
      '😒',
      '🙄',
      '😬',
      '😮‍💨',
      '🤥',
      '😌',
      '😔',
      '😪',
      '🤤',
      '😴',
      '😷',
      '🤒',
      '🤕',
      '🤢',
      '🤮',
      '🤧',
      '🥵',
      '🥶',
      '🥴',
      '😵',
      '🤯',
      '🤠',
      '🥳',
      '😎',
      '🤓',
      '😕',
      '😟',
      '🙁',
      '😮',
      '😯',
      '😲',
      '😳',
      '🥺',
    ],
    '❤️': [
      '❤️',
      '🧡',
      '💛',
      '💚',
      '💙',
      '💜',
      '🖤',
      '🤍',
      '💔',
      '❣️',
      '💕',
      '💞',
      '💓',
      '💗',
      '💖',
      '💘',
      '💝',
      '💟',
      '😈',
      '👿',
      '💀',
      '☠️',
      '👻',
      '👽',
      '🤖',
      '💩',
      '😺',
      '😸',
      '😹',
      '😻',
      '😼',
      '😽',
      '🙀',
      '😿',
      '😾',
      '🙈',
      '🙉',
      '🙊',
      '💋',
      '💌',
      '💍',
      '💎',
      '💐',
      '🌸',
      '💐',
      '🌺',
      '🌻',
      '🌹',
      '🌷',
      '🌱',
      '🌲',
      '🌳',
      '🌴',
      '🌵',
      '🌾',
      '🌿',
    ],
    '👀': [
      '👀',
      '👁️',
      '👅',
      '👄',
      '👋',
      '🤚',
      '🖐️',
      '✋',
      '🖖',
      '👌',
      '🤌',
      '🤏',
      '✌️',
      '🤞',
      '🤟',
      '🤘',
      '🤙',
      '👈',
      '👉',
      '👆',
      '🖕',
      '👇',
      '☝️',
      '🫵',
      '👍',
      '👎',
      '✊',
      '👊',
      '🤛',
      '🤜',
      '👏',
      '🙌',
      '👐',
      '🤲',
      '🤝',
      '🙏',
      '✍️',
      '💅',
      '🤳',
      '💪',
      '🦾',
      '🦿',
      '🦵',
      '🦶',
      '👂',
      '🦻',
      '👃',
      '🧠',
      '🫀',
      '🫁',
      '🦷',
      '🦴',
      '👀',
      '👁️',
      '👅',
      '👄',
    ],
    '🐶': [
      '🐶',
      '🐱',
      '🐭',
      '🐹',
      '🐰',
      '🦊',
      '🐻',
      '🐼',
      '🐨',
      '🐯',
      '🦁',
      '🐮',
      '🐷',
      '🐸',
      '🐵',
      '🙈',
      '🙉',
      '🙊',
      '🐒',
      '🐔',
      '🐧',
      '🐦',
      '🐤',
      '🐣',
      '🐥',
      '🦆',
      '🦅',
      '🦉',
      '🦇',
      '🐺',
      '🐗',
      '🐴',
      '🦄',
      '🐝',
      '🐛',
      '🦋',
      '🐌',
      '🐞',
      '🐜',
      '🪲',
      '🪳',
      '🦟',
      '🦗',
      '🕷️',
      '🕸️',
      '🦂',
      '🐢',
      '🐍',
      '🦎',
      '🦖',
      '🦕',
      '🐙',
      '🦑',
      '🦐',
      '🦞',
      '🦀',
    ],
    '🍎': [
      '🍎',
      '🍐',
      '🍊',
      '🍋',
      '🍌',
      '🍉',
      '🍇',
      '🍓',
      '🫐',
      '🍈',
      '🍒',
      '🍑',
      '🥭',
      '🍍',
      '🥥',
      '🥝',
      '🍅',
      '🍆',
      '🥑',
      '🥦',
      '🥬',
      '🥒',
      '🌶️',
      '🫑',
      '🌽',
      '🥕',
      '🧄',
      '🧅',
      '🥔',
      '🍠',
      '🥐',
      '🥖',
      '🍞',
      '🥨',
      '🥯',
      '🥞',
      '🧇',
      '🧈',
      '🍳',
      '🥞',
      '🧀',
      '🥚',
      '🍳',
      '🧈',
      '🥓',
      '🥩',
      '🍗',
      '🍖',
      '🌭',
      '🍔',
      '🍟',
      '🍕',
      '🫓',
      '🥪',
      '🥙',
      '🧆',
    ],
    '⚽': [
      '⚽',
      '🏀',
      '🏈',
      '⚾',
      '🥎',
      '🎾',
      '🏐',
      '🏉',
      '🥏',
      '🎱',
      '🪀',
      '🏓',
      '🏸',
      '🏒',
      '🏑',
      '🥍',
      '🏏',
      '🪃',
      '🥅',
      '⛳',
      '🪁',
      '🏹',
      '🎣',
      '🤿',
      '🥊',
      '🥋',
      '🎽',
      '🛹',
      '🛼',
      '🛷',
      '⛸️',
      '🥌',
      '🎿',
      '⛷️',
      '🏂',
      '🪂',
      '🏋️',
      '🤼',
      '🤸',
      '🤺',
      '⛹️',
      '🤾',
      '🏌️',
      '🏇',
      '🧘',
      '🏄',
      '🏊',
      '🤽',
      '🚣',
      '🧗',
      '🚵',
      '🚴',
      '🏆',
      '🥇',
      '🥈',
      '🥉',
    ],
    '🌈': [
      '🌍',
      '🌎',
      '🌏',
      '🌐',
      '🪐',
      '💫',
      '⭐',
      '🌟',
      '✨',
      '⚡',
      '☄️',
      '💥',
      '🔥',
      '🌪️',
      '🌈',
      '☀️',
      '🌤️',
      '⛅',
      '🌥️',
      '☁️',
      '🌦️',
      '🌧️',
      '⛈️',
      '🌩️',
      '🌨️',
      '🌀',
      '🌬️',
      '💨',
      '🌪️',
      '🌫️',
      '🌮',
      '🌯',
      '🗽',
      '🗼',
      '🏰',
      '🏯',
      '🏟️',
      '🎡',
      '🎢',
      '🎠',
      '⛲',
      '⛱️',
      '🏖️',
      '🏝️',
      '🏜️',
      '🌋',
      '⛰️',
      '🏔️',
      '🗻',
      '🏕️',
      '🏗️',
      '🏢',
      '🏠',
      '🏡',
      '🏘️',
      '🏚️',
    ],
    '💡': [
      '💡',
      '🔦',
      '🏮',
      '🪔',
      '📱',
      '📲',
      '💻',
      '🖥️',
      '🖨️',
      '⌨️',
      '🖱️',
      '🖲️',
      '💽',
      '💾',
      '💿',
      '📀',
      '📼',
      '📷',
      '📸',
      '📹',
      '🎥',
      '📽️',
      '🎞️',
      '📞',
      '☎️',
      '📟',
      '📠',
      '📺',
      '📻',
      '🎙️',
      '🎚️',
      '🎛️',
      '🧭',
      '⏱️',
      '⏲️',
      '⏰',
      '🕰️',
      '⌛',
      '⏳',
      '📡',
      '🔋',
      '🔌',
      '💎',
      '🔧',
      '🔨',
      '⚒️',
      '🛠️',
      '⛏️',
      '🔩',
      '⚙️',
      '🧱',
      '⛓️',
      '🧲',
      '🔫',
      '💣',
      '🧨',
    ],
    '🔣': [
      '🔣',
      '#️⃣',
      '*️⃣',
      '0️⃣',
      '1️⃣',
      '2️⃣',
      '3️⃣',
      '4️⃣',
      '5️⃣',
      '6️⃣',
      '7️⃣',
      '8️⃣',
      '9️⃣',
      '🔟',
      '🔠',
      '🔡',
      '🔤',
      '🅰️',
      '🆎',
      '🅱️',
      '🆑',
      '🆒',
      '🆓',
      'ℹ️',
      '🆔',
      'Ⓜ️',
      '🆕',
      '🆖',
      '🅾️',
      '🆗',
      '🅿️',
      '🆘',
      '🆙',
      '🆚',
      '🈁',
      '🈂️',
      '🈷️',
      '🈶',
      '🈯',
      '🉐',
      '㊙️',
      '㊗️',
      '🈺',
      '🈵',
      '🔴',
      '🟠',
      '🟡',
      '🟢',
      '🔵',
      '🟣',
      '⚫',
      '⚪',
      '🟤',
      '🔺',
      '🔻',
      '🔸',
    ],
  };

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: _categories.length, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final colors = MobileColors.of(context);
    return Container(
      height: 260,
      decoration: BoxDecoration(
        color: colors.surface,
        border: Border(top: BorderSide(color: colors.divider, width: 0.5)),
        borderRadius: BorderRadius.vertical(top: Radius.circular(12)),
      ),
      child: Column(
        children: [
          // 分类 Tab 条
          Container(
            decoration: BoxDecoration(
              color: colors.surface,
              border: Border(
                bottom: BorderSide(color: colors.divider, width: 0.5),
              ),
            ),
            child: TabBar(
              controller: _tabController,
              isScrollable: true,
              labelColor: MobileTheme.primaryOf(context),
              unselectedLabelColor: colors.textSecondary,
              labelStyle: const TextStyle(
                fontSize: 13,
                fontWeight: FontWeight.w600,
              ),
              unselectedLabelStyle: const TextStyle(fontSize: 13),
              indicatorColor: MobileTheme.primaryOf(context),
              indicatorWeight: 2,
              tabAlignment: TabAlignment.start,
              padding: const EdgeInsets.symmetric(horizontal: 8),
              tabs: _categories.map((c) {
                if (c.icon == null) {
                  return const Tab(text: '最近');
                }
                return Tab(text: c.icon);
              }).toList(),
            ),
          ),

          // 表情网格
          Expanded(
            child: TabBarView(
              controller: _tabController,
              children: _categories.map((category) {
                final emojis =
                    _categoryEmojis[category.icon] ?? _categoryEmojis[null]!;
                return _buildEmojiGrid(emojis);
              }).toList(),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildEmojiGrid(List<String> emojis) {
    return GridView.builder(
      padding: const EdgeInsets.all(8),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 8,
        childAspectRatio: 1,
      ),
      itemCount: emojis.length,
      itemBuilder: (context, index) {
        return GestureDetector(
          onTap: () => widget.onEmojiSelected(emojis[index]),
          child: Center(
            child: Text(emojis[index], style: const TextStyle(fontSize: 24)),
          ),
        );
      },
    );
  }
}

class _EmojiCategory {
  final String label;
  final String? icon; // null 表示最近
  const _EmojiCategory(this.label, this.icon);
}
