"""
handlers/__init__.py

Barrel export for the handlers package.

Each module contains standalone handler functions that are dispatched
by the TreeholeHandler in server.py.
"""
from handlers._admin_handler import (
    handle_admin_account_action,
    handle_admin_account_cancellation_requests,
    handle_admin_admin_accounts,
    handle_admin_add_channel,
    handle_admin_add_tag,
    handle_admin_announcement,
    handle_admin_announcements,
    handle_admin_auth_login,
    handle_admin_auth_logout,
    handle_admin_auth_me,
    handle_admin_change_password,
    handle_admin_channels_tags,
    handle_admin_config,
    handle_admin_create_account,
    handle_admin_delete_channel,
    handle_admin_delete_tag,
    handle_admin_image_review,
    handle_admin_images_reviews,
    handle_admin_overview,
    handle_admin_rename_channel,
    handle_admin_rename_tag,
    handle_admin_report_action,
    handle_admin_reports,
    handle_admin_reviews,
    handle_admin_review_batch,
    handle_admin_single_review,
    handle_admin_update_config,
    handle_admin_user_action,
    handle_admin_user_level_request_action,
    handle_admin_user_level_requests,
    handle_admin_users,
    handle_admin_appeals,
    handle_admin_appeal_action,
    handle_admin_post_pin_request_action,
    handle_admin_post_pin_requests,
    handle_admin_cancellation_action,
    handle_admin_export,
)
from handlers._auth_handler import (
    handle_login,
    handle_logout,
    handle_password_reset,
    handle_password_send_code,
    handle_register,
    handle_send_code,
    handle_verify,
)
from handlers._comment_handler import (
    handle_cancel_account_request,
    handle_level_upgrade_request,
)
from handlers._message_handler import (
    handle_accept_request,
    handle_block_peer,
    handle_delete_conversation,
    handle_direct_conversation,
    handle_get_conversations,
    handle_get_messages,
    handle_get_requests,
    handle_message_recall,
    handle_reject_request,
    handle_send_message,
    handle_send_request,
    handle_unblock_peer,
)
from handlers._notification_handler import (
    handle_get_notifications,
    handle_mark_all_notifications_read,
    handle_mark_notification_read,
)
from handlers._post_handler import (
    handle_create_comment,
    handle_create_post,
    handle_get_comments_mine,
    handle_get_post,
    handle_get_post_comments,
    handle_get_posts,
    handle_get_posts_favorites,
    handle_get_posts_mine,
    handle_get_report_detail,
    handle_get_reports_mine,
    handle_get_uploads_mine,
    handle_pin_request,
    handle_remove_favorite,
    handle_submit_appeal,
    handle_submit_report,
    handle_toggle_favorite,
    handle_toggle_like,
    handle_update_post,
    handle_delete_comment,
    handle_delete_post,
    handle_increment_view,
)
from handlers._static_handler import (
    handle_storage_get,
    handle_web_fallback_get,
)
from handlers._upload_handler import (
    handle_upload_avatar,
    handle_upload_image,
)
from handlers._user_handler import (
    handle_follow,
    handle_get_followers,
    handle_get_friends,
    handle_get_following,
    handle_get_me,
    handle_get_user,
    handle_unfollow,
    handle_update_me,
    handle_update_notification_preferences,
    handle_update_privacy,
)

__all__ = [
    # admin
    "handle_admin_account_action",
    "handle_admin_account_cancellation_requests",
    "handle_admin_admin_accounts",
    "handle_admin_add_channel",
    "handle_admin_add_tag",
    "handle_admin_announcement",
    "handle_admin_announcements",
    "handle_admin_auth_login",
    "handle_admin_auth_logout",
    "handle_admin_auth_me",
    "handle_admin_change_password",
    "handle_admin_channels_tags",
    "handle_admin_config",
    "handle_admin_create_account",
    "handle_admin_delete_channel",
    "handle_admin_delete_tag",
    "handle_admin_image_review",
    "handle_admin_images_reviews",
    "handle_admin_overview",
    "handle_admin_rename_channel",
    "handle_admin_rename_tag",
    "handle_admin_report_action",
    "handle_admin_reports",
    "handle_admin_reviews",
    "handle_admin_review_batch",
    "handle_admin_single_review",
    "handle_admin_update_config",
    "handle_admin_user_action",
    "handle_admin_user_level_request_action",
    "handle_admin_user_level_requests",
    "handle_admin_users",
    "handle_admin_appeals",
    "handle_admin_appeal_action",
    "handle_admin_post_pin_request_action",
    "handle_admin_post_pin_requests",
    "handle_admin_cancellation_action",
    "handle_admin_export",
    # auth
    "handle_login",
    "handle_logout",
    "handle_password_reset",
    "handle_password_send_code",
    "handle_register",
    "handle_send_code",
    "handle_verify",
    # comment / account
    "handle_cancel_account_request",
    "handle_level_upgrade_request",
    # message
    "handle_accept_request",
    "handle_block_peer",
    "handle_delete_conversation",
    "handle_direct_conversation",
    "handle_get_conversations",
    "handle_get_messages",
    "handle_get_requests",
    "handle_reject_request",
    "handle_send_message",
    "handle_send_request",
    "handle_unblock_peer",
    # notification
    "handle_get_notifications",
    "handle_mark_all_notifications_read",
    "handle_mark_notification_read",
    # post
    "handle_create_comment",
    "handle_create_post",
    "handle_get_comments_mine",
    "handle_get_post",
    "handle_get_post_comments",
    "handle_get_posts",
    "handle_get_posts_favorites",
    "handle_get_posts_mine",
    "handle_get_report_detail",
    "handle_get_reports_mine",
    "handle_get_uploads_mine",
    "handle_pin_request",
    "handle_remove_favorite",
    "handle_submit_appeal",
    "handle_submit_report",
    "handle_toggle_favorite",
    "handle_toggle_like",
    "handle_update_post",
    "handle_delete_comment",
    "handle_delete_post",
    "handle_increment_view",
    # static
    "handle_storage_get",
    "handle_web_fallback_get",
    # upload
    "handle_upload_avatar",
    "handle_upload_image",
    # user
    "handle_follow",
    "handle_get_followers",
    "handle_get_friends",
    "handle_get_following",
    "handle_get_me",
    "handle_get_user",
    "handle_unfollow",
    "handle_update_me",
    "handle_update_notification_preferences",
    "handle_update_privacy",
]
