@echo off
setlocal EnableExtensions EnableDelayedExpansion

cd /d "%~dp0"
set "BACKEND_HOST=0.0.0.0"
set "BACKEND_PORT=8080"

echo Restarting backend server on port %BACKEND_PORT%...
for /f "tokens=5" %%P in ('netstat -ano ^| findstr /R /C:":%BACKEND_PORT% .*LISTENING"') do (
  if not "%%P"=="0" (
    echo Stopping process %%P...
    taskkill /PID %%P /F >nul 2>nul
  )
)

timeout /t 1 /nobreak >nul
if not defined BACKEND_LAN_HOST (
  for /f "usebackq delims=" %%I in (`powershell -NoProfile -ExecutionPolicy Bypass -Command "$route = Get-NetRoute -DestinationPrefix '0.0.0.0/0' | Sort-Object RouteMetric, InterfaceMetric | Select-Object -First 1; if ($route) { Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $route.InterfaceIndex | Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254*' -and $_.AddressState -eq 'Preferred' } | Select-Object -First 1 -ExpandProperty IPAddress }"`) do (
    set "BACKEND_LAN_HOST=%%I"
  )
)

if defined BACKEND_LAN_HOST (
  > "miniprogram\config\env.local.js" (
    echo // Auto-generated by start_backend.bat. Do not commit.
    echo const localConfig = {
    echo   env: 'auto',
    echo   devtoolsBaseUrl: 'http://localhost:%BACKEND_PORT%',
    echo   lanBaseUrl: 'http://%BACKEND_LAN_HOST%:%BACKEND_PORT%',
    echo };
    echo.
    echo module.exports = localConfig;
  )
  echo Mini devtools: http://localhost:%BACKEND_PORT%
  echo Mini real device: http://%BACKEND_LAN_HOST%:%BACKEND_PORT%
  echo Mini config: miniprogram\config\env.local.js
) else (
  echo LAN IP not detected. Set BACKEND_LAN_HOST manually before running this script.
)

echo Starting backend server...
python backend\server.py
if errorlevel 1 (
  echo.
  echo Backend startup failed.
  pause
)
